### ISSUE TITLE
can i write spl programs use Orca programs to swap?

### ISSUE THREAD

**Issue by guijunchen** [orca-so/typescript-sdk#61]
it all knows: The Orca SDK contains a set of simple to use APIs to allow developers to integrate with the Orca exchange platform.

where is Orca programs code ? 
can i write spl program to integrate with the Orca exchange platform to swap? if can, where i can find demo.

**Comment by 0xscuba** [comment]
hi @guijunchen - orca-swap program shares the same interface as [token-swap](https://spl.solana.com/token-swap), so you can definitely integrate orca-swap via cpi
