### ISSUE TITLE
Why is the price checked by getQuote different from your official website

### ISSUE THREAD

**Issue by zhaowei0981** [orca-so/typescript-sdk#74]
Why is the price checked by getQuote different from your official website

**Comment by zhaowei0981** [comment]
` const connection = new Connection("https://api.mainnet-beta.solana.com", "singleGossip");
  const orca = getOrca(connection);`

**Comment by zhaowei0981** [comment]
USDT buy ORCA

Use typescript-sdk getQuote : 0.10237

official website: 0.10943

**Comment by 0xscuba** [comment]
@zhaowei0981 - web has auto-routing that finds best execution path, but the sdk doesn't have this feature
